<?php
#ExpressEdit 3.01
/*
ExpressEdit is an integrated Theme Creation CMS
	Copyright (c) 2018   expressedit.org  
    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <https://www.gnu.org/licenses/>.*/
#Settings here can be overwritten in local Cfg.class.php file to prevent updating..
class Cfg_master {
	const Local_document_root='';//ie /var/www/ comma separated list of file path to local server, will allow local login and onscreen error message details..
	const Force_local_login=false;//if true must login for local developement Document root
	const EditmodeDb_update=false;//Update DB field check for databases if in editmode
	const Jquery_src='jquery.min.js'; //currently jquery-2.2.4.min.js
     const Debug_backtrace=true;
	const Error_exit=false;//false for production may be true for development exits on non fatal errors .       const Local_url='htdocs,localhost';//use comma separated of more than one development system. to determine whether local development system or production environment  may be changed in local Cfg files also 
	#the following php.ini directives pertain to image uploading and manipulation or video uploading and limits set in php.ini file in edit directory and in html files upload.  
     const Script_submit=true;//Allow script in textarea submit. Will override error generated by Mod_Security on Server.  Comment posts automatically have all tags stripped, ie not affected by setting.
     const Iframe_submit=true;//allow iframe submit ie.  video embed code.
     const Time_zone='';//optionally set local time zone overrides date_default_timezone_get(); ie 'America/New_York' or 'UTF' 
     const Pic_upload_max='15M';//limit image max size in Mbs..
     const Vid_upload_max='100M';//limit Video max size in Mbs..
     const Pdf_upload_max='10M';//upload pdf max size
     // run phpinfo() to see other limiting currently loaded ini configuration files for filesize   ie.  post_max_size  or upload_max_filesize
	const Memory_limit='300M';// //affects editmode ini_set  
	const Max_execution_time=15;//affects editmode ini_set in seconds
	###################
	const Overwrite=true;//set to false to prevent overwriting of icons and other misc page files if they exist
     const Overwrite_page_class=false;//Page class file refers to a file which can be customized to override or add to main system functions, add header scripts and other files on a per page basis. Set to true to overwrite even if they exist when maintenance option for page class file generate is chosen.
	const Conserve_image_cachespace=false;//limits cache where possible.
	##The following three settings will determine whether the local server development system if used requires a password..
	#use comma separated of more than one development system. to determine whether local development system or production environment.  May be changed in local Cfg files also
	#to disable login set Force_local_login to falsee and specify Local_document_root filename....
	//const Local_url='';//ie local developement system url to public directory leave empty if not used.. 
	###################
	//name of database with identical fields to main db for use in viewing backups 
	const Mysqlserver='';//dir can be manually configured here if not auto detected which may affect backups..   ie  ='C:/xampp/mysql/bin  on xampp windows default settings where the entire path needs to be specified for mysqldump backups
	#******Database Info**************
     const Secure_session=false;
	const Dbhost = 'localhost'; 
     const Check_request='returnedit'; //used if cache html page version is reactivated
   
     const Preg_color='/^([a-f]|[A-F]|[0-9]){3}(([a-f]|[A-F]|[0-9]){3})?$/';
     const Preg_email='/^[\w.-]+@[\w.-]+\.[A-Za-z]{2,6}$/';
     const Style=true; 
     const Wordwrap=100; //set line length for emails
	const Temp_ext='temp_passclass_ext'; 
	#database  tables
     const Directory_dir='directory';
	const Backups_table='backups_db';
     const Db_traffic_table='user_data';
     const Master_post_table='master_post';
     const Master_page_table='master_page';
     const Master_gall_table='master_gall';
     const Master_post_css_table='master_post_css';
     const Master_post_data_table='master_post_data';
     const Master_col_css_table='master_col_css'; 
     const Columns_table='columns';
	const Comment_table='comments';//not used currently
	#rwd defaults
	const Default_width_mode='maxwidth';//if not set
	const Db_tables='columns,comments,directory,master_col_css,master_gall,master_page,master_post,master_post_css,master_post_data';
     #Fields   Field ( and new table) updates must be further updated in function update_db for automatically updating of current working dbs and storage backup dbases etc.  
     const Col_fields='col_table_base,col_table,col_num,col_options,col_status,col_grid_clone,col_gridspace_right,col_gridspace_left,col_grid_width,col_tcol_num,col_primary,col_clone_target,col_clone_target_base,col_style,col_style2,col_temp,col_grp_bor_style,col_comment_style,col_comment_date_style,col_comment_view_style,col_date_style,col_width,col_hr,col_flex_box,col_class1,col_class2,col_class3,col_class4,col_class5,col_style3';
     const Col_fields_all='col_table_base,col_table,col_num,col_options,col_status,col_grid_clone,col_gridspace_right,col_gridspace_left,col_grid_width,col_tcol_num,col_primary,col_clone_target,col_clone_target_base,col_style,col_style2,col_temp,col_grp_bor_style,col_comment_style,col_date_style,col_comment_view_style,col_comment_date_style,col_width,col_hr,col_update,col_time,token,col_flex_box,col_class1,col_class2,col_class3,col_class4,col_class5,col_style3';
    const Col_flex_options='flex_display,col_max_flex,col_min_flex,flex_direction,flex_wrap,flex_justify_content,flex_align_items,flex_align_content,,,,';//leaving additional room for flex otpion on end as record will record 3 times for each of 3 separate potential media queries
     const Blog_flex_options='blog_max_flex,blog_min_flex,flex_order,flex_grow,flex_shrink,flex_basis,flex_align_self,blog_flex_on,,,';//leaving additional option room on end as record will record 3 times for each of 3 separate potential media queries
	const Gallery_fields='master_gall_status,master_table_ref,master_gall_ref,gall_ref,gall_table,pic_order,picname,imagetitle,description,subtitle,width,height,galleryname,temp_pic_order,reset_id';
     const Post_fields='blog_clone_table,blog_col,blog_order,blog_type,blog_table,blog_gridspace_right,blog_gridspace_left,blog_grid_width,blog_data1,blog_data2,blog_data3,blog_data4,blog_data5,blog_data6,blog_data7,blog_data8,blog_data9,blog_data10,blog_data11,blog_data12,blog_data13,blog_data14,blog_data15,blog_tiny_data1,blog_tiny_data2,blog_tiny_data3,blog_tiny_data4,blog_tiny_data5,blog_tiny_data6,blog_tiny_data7,blog_tiny_data8,blog_tiny_data9,blog_tiny_data10,blog_tiny_data11,blog_tiny_data12,blog_tiny_data13,blog_tiny_data14,blog_tiny_data15,blog_grid_clone,blog_style,blog_style2,blog_table_base,blog_text,blog_border_start,blog_border_stop,blog_global_style,blog_date,blog_width,blog_width_mode,blog_status,blog_unstatus,blog_clone_target,blog_target_table_base,blog_float,blog_unclone,blog_pub,blog_tag,blog_temp,blog_options,blog_flex_box,blog_style3';
     const Page_fields='page_custom_css,page_head,page_ref,page_title,page_filename,page_width,page_pic_quality,page_style,page_style2,page_style3,page_options,page_break_points,page_cache,page_light_editor_value,page_dark_editor_value,page_dark_editor_order,page_light_editor_order,page_comment_style,page_date_style,page_comment_view_style,page_comment_date_style,page_style_day,page_style_month,page_grp_bor_style,page_link,page_link_hover,keywords,metadescription,page_data1,page_data2,page_data3,page_data4,page_data5,page_data6,page_data7,page_data8,page_data9,page_data10,use_tags,page_hr,page_h1,page_h2,page_h3,page_h4,page_h5,page_h6,page_myclass1,page_myclass2,page_myclass3,page_myclass4,page_myclass5,page_myclass6,page_myclass7,page_myclass8,page_myclass9,page_myclass10,page_myclass11,page_myclass12,page_tiny_data1,page_tiny_data2,page_tiny_data3,page_tiny_data4,page_tiny_data5,page_tiny_data6,page_tiny_data7,page_tiny_data8,page_tiny_data9,page_tiny_data10,page_clipboard'; 
	const Page_fields_all='page_custom_css,page_head,page_ref,page_title,page_filename,page_width,page_pic_quality,page_style,page_style2,page_style3,page_options,page_break_points,page_cache,page_light_editor_value,page_dark_editor_value,page_dark_editor_order,page_light_editor_order,page_comment_style,page_date_style,page_comment_view_style,page_comment_date_style,page_style_day,page_style_month,page_grp_bor_style,page_link,page_link_hover,keywords,metadescription,page_data1,page_data2,page_data3,page_data4,page_data5,page_data6,page_data7,page_data8,page_data9,page_data10,use_tags,page_hr,page_h1,page_h2,page_h3,page_h4,page_h5,page_h6,page_myclass1,page_myclass2,page_myclass3,page_myclass4,page_myclass5,page_myclass6,page_myclass7,page_myclass8,page_myclass9,page_myclass10,page_myclass11,page_myclass12,page_tiny_data1,page_tiny_data2,page_tiny_data3,page_tiny_data4,page_tiny_data5,page_tiny_data6,page_tiny_data7,page_tiny_data8,page_tiny_data9,page_tiny_data10,page_clipboard,page_update,page_time,token';
	const Dir_fields='dir_menu_id,dir_menu_style,dir_menu_order,dir_sub_menu_order,dir_filename,dir_title,dir_ref,dir_gall_table,dir_blog_table,dir_menu_type,dir_is_gall,dir_gall_type,dir_menu_opts,dir_hide_sub_menu,dir_external,dir_internal,dir_temp,dir_temp2';
	const Comment_fields='com_blog_id,com_text,com_name,com_email,com_token,com_status';
    #indexes
     const Background_styles='background_color,background_gradient_type,background_gradient_color1,background_gradient_color2,background_gradient_color3,background_gradient_color4,background_gradient_color5,background_gradient_color6,background_gradient_transparency1,background_gradient_transparency2,background_gradient_transparency3,background_gradient_transparency4,background_gradient_transparency5,background_gradient_transparency6,background_gradient_color_stop1,background_gradient_color_stop2,background_gradient_color_stop3,background_gradient_color_stop4,background_gradient_color_stop5,background_gradient_color_stop6,background_gradient_position_keyword,background_gradient_position1,background_gradient_position2,background_image,background_image_use,background_repeat,background_horiz,background_vert,background_opacity,background_size,background_pos_width,background_pos_height,background_image_opacity,background_fixed,background_image_none,background_image_noresize,background_video,background_video_ratio,background_video_display,background_image_off,background_color_off,background_parallax_reverse,background_size_units';
     const Style_functions=',padding_top,padding_bottom,padding_left,padding_right,margin_top,margin_bottom,margin_left,margin_right,font_family,font_size,font_weight,text_align,font_color,italics_font,small_caps,line_height,letter_spacing,text_underline,width_special,background,radius_corner,columns,text_shadow,box_shadow,transform,borders,height_special,temp_replace,outlines,float,media_max_width,media_min_width,width_max_special,width_min_special,width_media_unit,flex_item_width,flex_container_width,left,right,top,position_class,animate_class,fade_this,display_media,height_special,height_max_special,height_min_special,css_extension,media_styler,vertical,padding_all,margin_all,custom_style,font_media_unit';
     const Style_functions_order='background,padding_all,padding_top,padding_bottom,padding_left,padding_right,margin_top,margin_bottom,margin_all,margin_left,margin_right,font_color,text_shadow,font_family,font_size,font_media_unit,font_weight,text_align,line_height,letter_spacing,italics_font,small_caps,text_underline,radius_corner,borders,box_shadow,outlines,columns,transform';
	 const Style_functions_order_all='width_special,width_max_special,width_min_special,width_media_unit,width_media_unit,flex_container_width,flex_item_width,float,vertical,animate_class,fade_this,display_media,height_special,height_max_special,height_min_special,background,padding_all,padding_top,padding_bottom,padding_left,padding_right,margin_all,margin_top,margin_bottom,margin_left,margin_right,font_color,text_shadow,font_family,font_size,font_media,unit,font_weight,text_align,line_height,letter_spacing,italics_font,small_caps,text_underline,radius_corner,borders,box_shadow,outlines,columns,transform';
	const Page_options='page_editor_choice,page_darkeditor_background,page_darkeditor_color,page_lighteditor_background,page_lighteditor_color,page_date_format,page_max_expand_image,page_editor_fontfamily,page_editor_fontsize,page_slideshow,page_rem_scale_enable,page_min_width,,page_image_quality,page_backup_copies,page_advanced,page_editor_bordersize,page_alink_hover_color,page_rem_scale_upper,page_rem_scale_lower,page_mod_percent,page_rem_unit,page_grid_units,page_darkeditor_info,page_lighteditor_info,page_darkeditor_red,page_lighteditor_red,page_darkeditor_pos,page_lighteditor_pos,page_tiny_cache,page_tiny_min,page_carousel_cache,page_carousel_min,page_parallax,page_parallax_minwidth,page_enable_media_style';
	const Page_options_order='page_rem_unit,page_rem_scale_enable,page_rem_scale_upper,page_rem_scale_lower,page_mod_percent,page_max_expand_image,page_backup_copies,page_advanced,page_editor_fontfamily,page_editor_fontsize,page_slideshow,page_image_quality,page_editor_bordersize,page_alink_hover_color,page_grid_units,page_tiny_cache,page_tiny_min,page_carousel_cache,page_carousel_min';
	const Image_options='image_width_limit,image_noexpand,image_max_expand,image_quality,image_noresize,image_min,image_height_set,imagecaption_height,image_caption_text,image_caption_hover,image_internal_link,image_external_link,imagecaption_bottom,image_internal_query,image_height_media,image_max_media1,image_min_media1,image_max_media2,image_min_media2,image_max_media3,image_min_media3,image_max_media4,image_min_media4,image_max_media5,image_min_media5,image_per1,image_per2,image_per3,image_per4,image_per5';//accessed global edit &  add_page_pic
      const Blog_options='blog_comment,blog_comment_display,blog_editor_use,blog_date_on,blog_date_format,blog_enable_media_style,,blog_break_points,blog_vert_pos,blog_media_minmax,blog_display_fadethis_animate,blog_display_state_px,blog_animation,blog_opacity,blog_position,blog_width_alt_opt,blog_min_width_alt_opt,blog_max_width_alt_opt,blog_height_media,blog_height_opt,blog_min_height_opt,blog_max_height_opt,blog_pos_vert_val,blog_pos_horiz_val,blog_overflowx,blog_overflowy,blog_custom_class,blog_pos_vert_val1,blog_pos_horiz_val1,blog_pos_vert_val2,blog_pos_horiz_val2,blog_parallax_stellar,blog_sticky,';
     const Blog_options_order='blog_width_alt_opt,blog_animation,blog_parallax_stellar,blog_sticky,blog_display_fadethis_animate,blog_display_state_px,blog_opacity,blog_position,blog_pos_vert_val,blog_pos_horiz_val,blog_pos_vert_val1,blog_pos_horiz_val1,blog_pos_vert_val2,blog_pos_horiz_val2,blog_min_width_alt_opt,blog_max_width_alt_opt,blog_height_media,blog_height_opt,blog_min_height_opt,blog_max_height_opt,blog_custom_class,blog_vert_pos,blog_overflowx,blog_overflowy,blog_comment,blog_comment_display,blog_editor_use,blog_date_on,blog_date_format,blog_enable_media_style';
	const Column_options='col_tag_display,col_class_style,col_use_grid,col_grid_units,,col_vert_pos,col_enable_media_style,col_display_fadethis_animate,col_display_state_px,,,col_animation,col_opacity,col_position,col_enable_masonry,col_enable_group_style,col_width_alt_opt,col_min_width_alt_opt,col_max_width_alt_opt,col_pos_vert_val,col_pos_horiz_val,col_height_opt,col_min_height_opt,col_max_height_opt,col_overflowx,col_overflowy,col_height_media,col_pos_vert_val1,col_pos_horiz_val1,col_pos_vert_val2,col_pos_horiz_val2,col_custom_class,col_parallax_stellar,col_sticky';// 
	const Column_options_order='col_width_alt_opt,col_min_width_alt_opt,col_max_width_alt_opt,col_animation,col_parallax_stellar,col_sticky,col_display_fadethis_animate,col_display_state_px,col_enable_masonry,col_opacity,col_position,col_pos_vert_val,col_pos_horiz_val,col_height_opt,col_min_height_opt,col_max_height_opt,col_overflowx,col_overflowy,col_height_media,col_pos_vert_val1,col_pos_horiz_val1,col_pos_vert_val2,col_pos_horiz_val2,col_custom_class,col_tag_display,col_use_grid,col_grid_units,col_vert_pos,col_class_style,col_enable_media_style,col_enable_group_style';// 
     const Position_options='position,position_max,position_min,position_horiz,position_horiz_val,position_vert,position_vert_val,position_zindex,position_pos_neg,position_opacity,position_important,position_orientation,position_operator';
     const Opacity_options='opacity,opacity_max,opacity_min,opacity_orientation,opacity_operator';
	const Box_shadow_options='shadowbox_horiz_offset,shadowbox_vert_offset,shadowbox_blur_radius,shadowbox_spread_radius,shadowbox_color,shadowbox_insideout,shadowbox_opacity,shadowbox_units';
     const Display_options='display_max,display_min,display_distance,display_fade_choice,display_offset,display_reverse,display_speed,display_force_off';
	const Animation_options='animate_type,animate_visibility,animate_repeats,animate_duration,animate_height,animate_width,animate_after_type,animate_after_delay,animate_after_repeats,animate_after_duration,animate_final_display,animate_alternate,animate_lock,animate_complete_id,animate_sibling,animate_prior_delay,animate_max1,animate_min1,animate_type1,animate_visibility1,animate_max2,animate_min2,animate_type2,animate_visibility2,animate_max3,animate_min3,animate_type3,animate_visibility3';
	const Animation_types='none,skewSubtle,transformScale1,transformScale3,transformScale5,transformScale7,transformScale8,transformScale9,transformScale11,transformScale12,transformScale15,hoverScale05,hoverScale1,hoverScale2,hoverScale3,hoverScale4,hoverScale5,fadeInUpSubtleScale,fadeInDownSubtleScale,fadeInLeftSubtleScale,fadeInRightSubtleScale,bounce,flash,pulse,rubberBand,shake,swing,tada,wobble,jello,bounceIn,bounceInDown,bounceInLeft,bounceInRight,bounceInUp,bounceOut,bounceOutDown,bounceOutLeft,bounceOutRight,bounceOutUp,fadeIn,fadeIn,fadeInDownSubtle,fadeInDown,fadeInDownBig,fadeInLeft,fadeInLeftBig,fadeInRight,fadeInRightBig,fadeInUpSubtle,fadeInUp,fadeInUpBig,fadeOut,fadeOutDownSubtle,fadeOutDown,fadeOutDownBig,fadeOutLeft,fadeOutLeftBig,fadeOutRight,fadeOutRightBig,fadeOutUpSubtle,fadeOutUp,fadeOutUpBig,flip,flipInX,flipInY,flipOutX,flipOutY,lightSpeedIn,lightSpeedOut,rotateIn,rotateInDownLeft,rotateInDownRight,rotateInUpLeft,rotateInUpRight,rotateOut,rotateOutDownLeft,rotateOutDownRight,rotateOutUpLeft,rotateOutUpRight,slideInUp,slideInDown,slideInLeft,slideInRight,slideOutUp,slideOutDown,slideOutLeft,slideOutRight,zoomIn,zoomInDown,zoomInLeft,zoomInRight,zoomInUp,zoomOut,zoomOutDown,zoomOutLeft,zoomOutRight,zoomOutUp,hinge,jackInTheBox,rollIn,rollOut';
	const Main_width_options='blog_width_mode,blog_percent_init,blog_marginleft_init,blog_marginright_init,blog_media_1,blog_percent_1,blog_marginleft_1,blog_marginright_1,blog_media_2,blog_percent_2,blog_marginleft_2,blog_marginright_2,blog_media_3,blog_percent_3,blog_marginleft_3,blog_marginright_3,blog_media_4,blog_percent_4,blog_marginleft_4,blog_marginright_4,blog_media_5,blog_percent_5,blog_marginleft_5,blog_marginright_5,blog_media_6,blog_percent_6,blog_marginleft_6,blog_marginright_6,blog_media_7,blog_percent_7,blog_marginleft_7,blog_marginright_7,blog_media_8,blog_percent_8,blog_marginleft_8,blog_marginright_8,blog_width_unit_init,blog_width_unit1,blog_width_unit2,blog_width_unit3,blog_width_unit4,blog_width_unit5,blog_width_unit6,blog_width_unit7,blog_width_unit8';
     const Class_width_options='class_width_toggle,class_width_unit,class_width_init,class_marginleft_init,class_marginright_init,class_media_1,class_width_1,class_marginleft_1,class_marginright_1,class_media_2,class_width_2,class_marginleft_2,class_marginright_2,class_media_3,class_width_3,class_marginleft_3,class_marginright_3,class_media_4,class_width_4,class_marginleft_4,class_marginright_4,class_media_5,class_width_5,class_marginleft_5,class_marginright_5,class_media_6,class_width_6,class_marginleft_6,class_marginright_6,class_media_7,class_width_7,class_marginleft_7,class_marginright_7,class_media_8,class_width_8,class_marginleft_8,class_marginright_8,class_unit1,class_unit2,class_unit3,class_unit4,class_unit5,class_unit6,class_unit7,class_unit8';
	const Class_font_options='class_font_toggle,class_font_unit,class_font_init,class_media_1,class_font_1,class_media_2,class_font_2,class_media_3,class_font_3,class_media_4,class_font_4,class_media_5,class_font_5,class_media_6,class_font_6,class_media_7,class_font_7,class_media_8,class_font_8';
     const Backup_copies=200;//change  in page_default settings
	const Column_grid_units=100;//default setting change in page configs
	const Column_break_points='1006,791,489,384';//default setting change in page configs
	const Development=true;//for javascript alert on ajax imagecall and build image and image resize messages on editpage and append file ?randomnumber 
     #prefixes  suffixes  extenisons
     const Exts='htm,html,asp';
     const Backup_ext_folder='backupversions/';
     const Post_suffix='_post_id';
     const Col_suffix='_col_id';
     const Post_prefix='post_';
     const Blog_prefix='blog_';//for fields
     const Col_prefix='col_';
	const Page_prefix='page_';
     //const Gall_ref_ext='data';
     const Expand_ref_ext='expand';
     #Files  and file extensions 
     const Log_file='mylog.txt';
     const Success_file='success.txt';
     const Db_ext='.sql';
     const Aux_scripts='add_page_pic,add_page_vid';//like to prevent return link when editing
     //const Table_suffix='data,highslide,expand,_thumbs';
     const Exclude='jpgraph,tinymce-Orig,1downloaded internet files,fvd suite,zen cart,secure apache ssl,.,..,$recycle.bin,system volume information,temp,phplist,compress,zen,phpMyAdmin,phpsite,ellen,design,css,create,arthur,attachment,highslide,fonts,langs,plugins,themes,utils,graphics,tmp,cgi-bin,forum,zen,wordpress,tinymce,tiny-mce';#these files are excluded from search and other generation programs
    #pdf
     const Valid_pdf_mime='application/pdf,application/acrobat,application/x-pdf,applications/vnd.pdf,text/pdf,text/x-pdf';
     const Pdf_max=15000000;
	const Pass_class_page='passclass.php';
	const Expand_pass_page='expand-passclass.php';
      #directories-non Image or Vid
     const Menu_icon_dir='menu_icons/';
     const Data_dir='data/';
     const Buffer_dir='buffer/';
     const Gall_info_dir='gall_info_dir/';
     const Image_info_dir='image_info_dir/';
	const Page_info_dir='page_info_dir/';
     const Auto_slide_dir='auto_slide/';
     const Carousel_slide_dir='carousel_dir/';
	const Image_noresize_dir='image_noresize/';
	const Graphics_dir='graphics/';
     const Social_dir='socialicons/';
     const Contact_dir='contacts/';
     const Font_dir='fonts/';
     const Display_dir='display';
     const Backup_dir='backups/';
     const Master_dir='master/';
	const Image100_dir='imagedir100/';
     const Common_dir='common_dir/';//A repository of common files and video drectory used to install on sub-domains
	const Logfile_dir='logfile/';
     const Include_dir='includes/';
     const Upload_dir='uploads/';
     const Tiny_resize_dir='tiny_resize/';
     const Tiny_upload_dir='tiny_uploads/';
     const Tiny_orig_sz_dir='tiny_orig_sz/';
     const Script_dir='scripts/';
	const Response_dir_prefix='imagedir';
     const Style_dir='styling/';
	const Css_dir='styling/';
     const Tinymce_user_dir='styling/tiny_mce/'; 
	const Theme_dir='theme_hold/'; 
	const Theme_match='theme'; 
      #**Image Directories ********
     const Tiny_cache_min='400';
     const Carousel_cache_min='400';
     const Favicon='karma.ico';
     const Playbutton_dir='playbutton/';
     const Watermark_dir='watermarks/';
     const Background_image_dir='background_images/';
     const Small_thumb_dir='small_images/';
     const Large_image_dir='large_images/';//for gallery
     const Master_thumb_dir='master_thumbs/'; 
     const Page_images_dir='page_images/';
     const Page_images_expand_dir='page_images_expanded/';
     #***Image Info*****************************
     #Image_response values must asccend
     const Page_width='1600';//sets default page width if no column widths set..
     const Tiny_image_cache='400,500,700,900,1100';
     const Carousel_image_cache='400,500,700,900';
     const Image_response='100,200,300,400,500,700,900,1100,1300,1700,2100';//default  px sises for image cache directories
     const Default_video_img='default_vid.jpg';
	const Pass_image='default_pass.jpg';
	const Default_image='default.jpg';
	const Overlay_png='overlay.png';
     ####
      // these image size settings are defaults or maxwidths .. Pic image sizes generally occupy full space of post available up to any max values set..
     const Max_pic_width=3000;//max pic width for body background images
     const Default_watermark=false;//watermark may be added through uploads interface
     const Small_gall_pic_plus='180';//default backup   config in your gall post settings
     const Small_gall_pic_width='180';//default backup  config in your gall post settings
	const Master_gall_pic_plus='200';//master gall setting  config in your gall post settings
     const Large_gall_pic_plus='700';//default backup  config in your gall post settings
     const Large_gall_pic_width='700';//default backup  config in your gall post settings
     const Page_pic_expand_plus='3000'; //default value set in page options..
     ####
     const Valid_pic_mime =   'image/pjpeg,image/jpeg,image/JPG,image/gif,image/GIF,image/X-PNG,image/PNG,image/png,image/x-png'; //,image/svg+xml
     const Valid_pic_ext='jpg,gif,png,jpeg';
     const Valid_watermark_ext="gif,png";
     const Valid_pdf_ext='pdf';
     const Pic_quality=95;
	const Col_maxwidth=4000;
     const Master_gall_pic_width=300;//this is the large thumbnails to go to expanded gallery t 
     const Default_background_image_width=500;//sets default width
     #*********Gallery Management*********
     const Gallery_content='';//blank default   gallery for master gallery
     
     #*************
     const Last_log='last_logfile.txt'; //file with the last log only
     #**Video+++++++++++
     const Vid_button='playvid.gif';  //watermark  play button automatically added to uploaded video still images
     const Vid_background_dir='video_background/'; 
     const Vid_dir='video/';  
     const Video_dir='video/'; 
     const Vid_image_dir='video_image/';                   
     const Valid_vid_mime =  'video/mp4,video/webm,video/ogg,video/m4v';
     const Valid_vid_ext='mp4,ogg,m4v,webm';
     #**Contact++++++++++
     #see local cfg file  Cfg.class.php in Public Home includes
      #***************************
      
     const Fonts_browser='Arial, Helvetica, sans-serif; Arial Black, Gadget, sans-serif; Constantia, cambria, sans-serif; Comic Sans MS, Comic Sans MS5, cursive; Courier New, monospace; Georgia1, Georgia, serif; Helvetica, sans-serif; Impact, Impact5, Charcoal6, sans-serif; Lucida Console, Monaco5, monospace; Lucida Sans Unicode, Lucida Grande, sans-serif; Palatino Linotype, Book Antiqua3, Palatino, serif; Tahoma, Geneva, sans-serif; Times New Roman, Times New Roman, Times, serif; Trebuchet MS1, Trebuchet MS, sans-serif; Verdana, Verdana, Geneva, sans-serif';
     const Fonts_extended='Chancur;Miama;MeathFLF;Fely;GothicA1;Hind;Allura;Questrial;Nova Slim;Cabin;Julee;Macondo Swash Caps;Michroma;Give You Glory;Delius Swash Caps;Bad Script;Sofia;Eagle Lake;Kite One;Contrail One;Paprika;Redressed,cursive;Shadows Into Light;Josefin Slab;Antic;Nothing You Could Do;Indie Flower;Delius;Amaranth;Over the Rainbow;Aubrey;Text Me One;Cinzel Decorative;Shadows Into Light Two;Comfortaa;Handlee;Oxygen;Basic;Ruluko;Chivo;Architects Daughter;Merienda;Diplomata SC;Cedarville Cursive;Numans;Happy Monkey;Sintony;bangbang;';
     #***************************
     #Colors  You can change the value of color on the editor value at top Page Configs
    
     #You can independently change colors and color order for light and dark themes in the editor
     const Pos_color='64C91D';// success color  and column level 1 color
     const RedAlert_color='c82c1d';//alert messages  often a problem
     const Info_color='e5d805'; //information hover and instructional message.. etc.
	const Navy_color='2B1DC9';
	#the order of these text editor colors and border colors corresponds to the column level.. top colors used much  more frequently
	##  DO NOT CHANGE ORDER HERE OR VALUES WILL BE MIXED..  CHANGE ORDER IN EDITOR UNDER CONFIG THIS PAGE AT TOP.  ADD COLORS HERE ANYWHERE THEN RESET in Maintenance Mode.
	#Color values (default) are now set in global_master class protected vals (top of page);
	#Additional color map colors provided from 
	const Text_color_map='"CDFFF5", "lightlightaqua", "ffefd5", "papayawhip", "afeeee", "paleturquoise", "eee8aa", "palegoldenrod", "fdf5e6", "oldlace", "dcdcdc", "gainsboro", "b0e0e6", "powderblue", "8fbc8f", "darkseagreen", "00ffff", "aqua", "ffffff", "white", "1e90ff", "dodgerblue", "800000", "maroon", "2B1DC9", "navy", "C91B45", "cherry", "00ff00", "brightgreen", "ff4500", "orangered", "ff6600", "orange", "c6a5a5", "lightmaroon", "0075a0", "ekblue", "816227", "brown", "266a2e", "green", "FFFF00", "yellow", "a9a9a9", "darkgrey", "dccbcb", "lightermaroon", "bdb76b", "darkkhaki", "8b008b", "darkmagenta", "556b2f", "darkolivegreen", "ff8c00", "darkorange", "9932cc", "darkorchid", "8b0000", "darkred", "e9967a", "darksalmon", "483d8b", "darkslateblue", "2f4f4f", "darkslategray", "d87093", "palevioletred", "98fb98", "palegreen", "00ced1", "darkturquoise", "9400d3", "darkviolet", "ff1493", "deeppink", "696969", "dimgrey", "b22222", "firebrick", "fffaf0", "floralwhite", "228b22", "forestgreen", "ff00ff", "fuchsia", "ffe4b5", "moccasin", "ff00ff", "magenta", "808000", "olive", "6b8e23", "olivedrab", "da70d6", "orchid", "00bfff", "deepskyblue", "ffdab9", "peachpuff", "ffdead", "navajowhite", "cd853f", "peru", "dda0dd", "plum", "bc8f8f", "rosybrown", "4169e1", "royalblue", "8b4513", "saddlebrown", "fa8072", "salmon", "f4a460", "sandybrown", "2e8b57", "seagreen", "ede5e5", "lightestmaroon", "000000", "black", "e5d805", "gold", "7AFFE8", "lighteraqua", "04B18D", "darkeraqua", "0FCEA6", "darkaqua", "ffebee", "red lighten-5", "ffcdd2", "red lighten-4", "ef9a9a", "red lighten-3", "e57373", "red lighten-2", "ef5350", "red lighten-1", "f44336", "red", "e53935", "red darken-1", "d32f2f", "red darken-2", "c62828", "red darken-3", "b71c1c", "red darken-4", "ff8a80", "red accent-1", "ff5252", "red accent-2", "ff1744", "red accent-3", "d50000", "red accent-4", "fce4ec", "pink lighten-5", "f8bbd0", "pink lighten-4", "f48fb1", "pink lighten-3", "f06292", "pink lighten-2", "ec407a", "pink lighten-1", "e91e63", "pink", "d81b60", "pink darken-1", "c2185b", "pink darken-2", "ad1457", "pink darken-3", "880e4f", "pink darken-4", "ff80ab", "pink accent-1", "ff4081", "pink accent-2", "f50057", "pink accent-3", "c51162", "pink accent-4", "f3e5f5", "purple lighten-5", "e1bee7", "purple lighten-4", "ce93d8", "purple lighten-3", "ba68c8", "purple lighten-2", "ab47bc", "purple lighten-1", "9c27b0", "purple", "8e24aa", "purple darken-1", "7b1fa2", "purple darken-2", "6a1b9a", "purple darken-3", "4a148c", "purple darken-4", "ea80fc", "purple accent-5", "e040fb", "purple accent-5", "d500f9", "purple accent-5", "aa00ff", "purple accent-4", "ede7f6", "deep-purple lighten-5", "d1c4e9", "deep-purple lighten-4", "b39ddb", "deep-purple lighten-3", "9575cd", "deep-purple lighten-2", "7e57c2", "deep-purple lighten-1", "673ab7", "deep-purple", "5e35b1", "deep-purple darken-1", "512da8", "deep-purple darken-2", "4527a0", "deep-purple darken-3", "311b92", "deep-purple darken-4", "b388ff", "deep-purple accent-1", "7c4dff", "deep-purple accent-2", "651fff", "deep-purple accent-3", "6200ea", "deep-purple accent-4", "e8eaf6", "indigo lighten-5", "c5cae9", "indigo lighten-4", "9fa8da", "indigo lighten-3", "7986cb", "indigo lighten-2", "5c6bc0", "indigo lighten-1", "3f51b5", "indigo", "3949ab", "indigo darken-1", "303f9f", "indigo darken-2", "283593", "indigo darken-3", "1a237e", "indigo darken-4", "8c9eff", "indigo accent-1", "536dfe", "indigo accent-2", "3d5afe", "indigo accent-3", "304ffe", "indigo accent-4", "e3f2fd", "blue lighten-5", "bbdefb", "blue lighten-4", "90caf9", "blue lighten-3", "64b5f6", "blue lighten-2", "42a5f5", "blue lighten-1", "2196f3", "blue", "1e88e5", "blue darken-1", "1976d2", "blue darken-2", "1565c0", "blue darken-3", "0d47a1", "blue darken-4", "82b1ff", "blue accent-1", "448aff", "blue accent-2", "2979ff", "blue accent-3", "2962ff", "blue accent-4", "e1f5fe", "light-blue lighten-5", "b3e5fc", "light-blue lighten-4", "81d4fa", "light-blue lighten-3", "4fc3f7", "light-blue lighten-2", "29b6f6", "light-blue lighten-1", "03a9f4", "light-blue", "039be5", "light-blue darken-1", "0288d1", "light-blue darken-2", "0277bd", "light-blue darken-3", "01579b", "light-blue darken-4", "80d8ff", "light-blue accent-1", "40c4ff", "light-blue accent-2", "00b0ff", "light-blue accent-3", "0091ea", "light-blue accent-4", "e0f7fa", "cyan lighten-5", "b2ebf2", "cyan lighten-4", "80deea", "cyan lighten-3", "4dd0e1", "cyan lighten-2", "26c6da", "cyan lighten-1", "00bcd4", "cyan", "00acc1", "cyan darken-1", "0097a7", "cyan darken-2", "00838f", "cyan darken-3", "006064", "cyan darken-4", "84ffff", "cyan accent-1", "18ffff", "cyan accent-2", "00e5ff", "cyan accent-3", "00b8d4", "cyan accent-4", "e0f2f1", "teal lighten-5", "b2dfdb", "teal lighten-4", "80cbc4", "teal lighten-3", "4db6ac", "teal lighten-2", "26a69a", "teal lighten-1", "009688", "teal", "00897b", "teal darken-1", "00796b", "teal darken-2", "00695c", "teal darken-3", "004d40", "teal darken-4", "a7ffeb", "teal accent-1", "64ffda", "teal accent-2", "1de9b6", "teal accent-3", "00bfa5", "teal accent-4", "e8f5e9", "green lighten-5", "c8e6c9", "green lighten-4", "a5d6a7", "green lighten-3", "81c784", "green lighten-2", "66bb6a", "green lighten-1", "4caf50", "green", "43a047", "green darken-1", "388e3c", "green darken-2", "2e7d32", "green darken-3", "1b5e20", "green darken-4", "b9f6ca", "green accent-1", "69f0ae", "green accent-2", "00e676", "green accent-3", "00c853", "green accent-4", "f1f8e9", "light-green lighten-5", "dcedc8", "light-green lighten-4", "c5e1a5", "light-green lighten-3", "aed581", "light-green lighten-2", "9ccc65", "light-green lighten-1", "8bc34a", "light-green", "7cb342", "light-green darken-1", "689f38", "light-green darken-2", "558b2f", "light-green darken-3", "33691e", "light-green darken-4", "ccff90", "light-green accent-1", "b2ff59", "light-green accent-2", "76ff03", "light-green accent-3", "64dd17", "light-green accent-4", "f9fbe7", "lime lighten-5", "f0f4c3", "lime lighten-4", "e6ee9c", "lime lighten-3", "dce775", "lime lighten-2", "d4e157", "lime lighten-1", "cddc39", "lime", "c0ca33", "lime darken-1", "afb42b", "lime darken-2", "9e9d24", "lime darken-3", "827717", "lime darken-4", "f4ff81", "lime accent-1", "eeff41", "lime accent-2", "c6ff00", "lime accent-3", "aeea00", "lime accent-4", "fffde7", "yellow lighten-5", "fff9c4", "yellow lighten-4", "fff59d", "yellow lighten-3", "fff176", "yellow lighten-2", "ffee58", "yellow lighten-1", "ffeb3b", "yellow", "fdd835", "yellow darken-1", "fbc02d", "yellow darken-2", "f9a825", "yellow darken-3", "f57f17", "yellow darken-4", "ffff8d", "yellow accent-1", "ffff00", "yellow accent-2", "ffea00", "yellow accent-3", "ffd600", "yellow accent-4", "fff8e1", "amber lighten-5", "ffecb3", "amber lighten-4", "ffe082", "amber lighten-3", "ffd54f", "amber lighten-2", "ffca28", "amber lighten-1", "ffc107", "amber", "ffb300", "amber darken-1", "ffa000", "amber darken-2", "ff8f00", "amber darken-3", "ff6f00", "amber darken-4", "ffe57f", "amber accent-1", "ffd740", "amber accent-2", "ffc400", "amber accent-3", "ffab00", "amber accent-4", "fff3e0", "orange lighten-5", "ffe0b2", "orange lighten-4", "ffcc80", "orange lighten-3", "ffb74d", "orange lighten-2", "ffa726", "orange lighten-1", "ff9800", "orange", "fb8c00", "orange darken-1", "f57c00", "orange darken-2", "ef6c00", "orange darken-3", "e65100", "orange darken-4", "ffd180", "orange accent-1", "ffab40", "orange accent-2", "ff9100", "orange accent-3", "ff6d00", "orange accent-4", "fbe9e7", "deep-orange lighten-5", "ffccbc", "deep-orange lighten-4", "ffab91", "deep-orange lighten-3", "ff8a65", "deep-orange lighten-2", "ff7043", "deep-orange lighten-1", "ff5722", "deep-orange", "f4511e", "deep-orange darken-1", "e64a19", "deep-orange darken-2", "d84315", "deep-orange darken-3", "bf360c", "deep-orange darken-4", "ff9e80", "deep-orange darken-1", "ff6e40", "deep-orange darken-2", "ff3d00", "deep-orange darken-3", "dd2c00", "deep-orange darken-4", "efebe9", "brown lighten-5", "d7ccc8", "brown lighten-4", "bcaaa4", "brown lighten-3", "a1887f", "brown lighten-2", "8d6e63", "brown lighten-1", "795548", "brown", "6d4c41", "brown darken-1", "5d4037", "brown darken-2", "4e342e", "brown darken-3", "3e2723", "brown darken-4", "fafafa", "grey lighten-5", "f5f5f5", "grey lighten-4", "eeeeee", "grey lighten-3", "e0e0e0", "grey lighten-2", "bdbdbd", "grey lighten-1", "9e9e9e", "grey", "757575", "grey darken-1", "616161", "grey darken-2", "424242", "grey darken-3", "212121", "grey darken-4", "eceff1", "blue-grey lighten-5", "cfd8dc", "blue-grey lighten-4", "b0bec5", "blue-grey lighten-3", "90a4ae", "blue-grey lighten-2", "78909c", "blue-grey lighten-1", "607d8b", "blue-grey", "546e7a", "blue-grey darken-1", "455a64", "blue-grey darken-2", "37474f", "blue-grey darken-3", "263238", "blue-grey darken-4", "000000", "black", "ffffff", "white", "d0d6e2", "mdb-color lighten-5", "b1bace", "mdb-color lighten-4", "929fba", "mdb-color lighten-3", "7283a7", "mdb-color lighten-2", "59698d", "mdb-color lighten-1", "45526e", "mdb-color", "3b465e", "mdb-color darken-1", "2e3951", "mdb-color darken-2", "1c2a48", "mdb-color darken-3", "1c2331", "mdb-color darken-4"';
	const Light_editor_color_order='dodgerblue,maroon,navy,cherry,brightgreen,deepskyblue,orangered,aqua,orange,lightmaroon,ekblue,brown,green,yellow,darkgrey,lightermaroon,darkkhaki,darkmagenta,darkolivegreen,darkorange,darkorchid,darkred,darksalmon,darkseagreen,darkslateblue,darkslategray,darkturquoise,darkviolet,deeppink,dimgray,dimgrey,firebrick,floralwhite,forestgreen,fuchsia,gainsboro,moccasin,magenta,navajowhite,oldlace,olive,olivedrab,orchid,palegoldenrod,palegreen,paleturquoise,palevioletred,papayawhip,peachpuff,peru,plum,powderblue,rosybrown,royalblue,saddlebrown,salmon,sandybrown,seagreen,lightestmaroon,black,gold,white,lightlightaqua,lighteraqua,darkeraqua,darkaqua';
	##   YOU CAN  CHANGE ORDER IN EDITOR UNDER CONFIG THIS PAGE AT TOP or change here as needed and be sure to query database to remove values: UPDATE `master_page` SET page_dark_editor_order='',page_light_editor_order='',page_dark_editor_value='',page_light_editor_value='' which will then auto-generate if you change order at least once. change order of both light and dark to save auto generate time everytime...
	const Dark_editor_color_order='lightlightaqua,papayawhip,paleturquoise,palegoldenrod,oldlace,gainsboro,powderblue,darkseagreen,aqua,white,dodgerblue,maroon,navy,cherry,brightgreen,orangered,orange,lightmaroon,ekblue,brown,green,yellow,darkgrey,lightermaroon,darkkhaki,darkmagenta,darkolivegreen,darkorange,darkorchid,darkred,darksalmon,darkslateblue,darkslategray,palevioletred,palegreen,darkturquoise,darkviolet,deeppink,dimgrey,firebrick,floralwhite,forestgreen,fuchsia,moccasin,magenta,olive,olivedrab,orchid,deepskyblue,peachpuff,navajowhite,peru,plum,rosybrown,royalblue,saddlebrown,salmon,sandybrown,seagreen,lightestmaroon,black,gold,lighteraqua,darkeraqua,darkaqua';
//these colors are arranged for lighter to go with darker background
	//note: color names much match respective global_master  class  names
	//const Full_color_index='info,pos, redAlert ,cherry,aqua,brightgreen,yellow,ekblue,orange,navy,magenta,maroon,brown,green';
	#************************ 
     #backup configuration for cleaning sql and gzipped backups   settings may be tweaked based on your available server disk space	const Max_gz_backups=10; 
	 
}
?>