<?php
#ExpressEdit 2.0.4
class Cfg extends Cfg_master{
     #the following class constants require changing..
	const Encrypt_pass='$%*)^RTtCVrr12';//use strong password this is used in secure_login
     const Owner   = 'yourname';//Optional reference used in misc.
     const Dbpass= 'mypass';  //latest mysqli requirement: specific at least 1 of each: uppercase, special characters  numeric
     const Dbuser = 'prefix_myusername';//enter your database user name changing prefix to server prefix if used or remove
     const Dbhost='localhost';//typical setting 
     const Dbname='prefix_yourdbnamehere';//enter your dbname  changing prefix to server requirement if required or remove 
     const View_db='prefix_backupDb';//set up database that backups can be imported to for viewing ie a copy of Dbname except used for backup restoration.. put name here
     const PrimeEditDir = 'eddirnameXXX/'; // acts as secondary password make unobvious to prevent login attemps
     const Session_save_path='session_bgfhXaByzrt5';//specify a  unique session save path directory ..  use NO special characters 
	################### 
     const Script_submit=false;//Allow script in textarea submit. Will override error generated by Mod_Security on Server.  Comment and contact form posts automatically have all tags deactivated, ie not affected by setting.
     const Iframe_submit=true;// 
     #################
     #**Contact+++++++++++
     #contact form emails are configured in each contact form settings
	const Favicon='karma.ico';//tab image
	const Admin_email='sample@hotmail.com,sample@yahoo.com';//error reporting   comma separate emails
	const Contact_email='sample@hotmail.com';// Comment, feedback list of comma separated emails. Also used if contact form emails are not set. 
	const Mail_from='site@site.com';//optionally put a return mail from address.
     ##Sizes of Page/Post Images
	############ Customization/Maintenance/Development 
	//change the following here  to override  on this site or change for multiple sites in Cfg_master (.class.php)  parent settings if set up for multiple sites
     const Overwrite=Cfg_master::Overwrite;// for copy over writing of common files such as certain icons and images, and editfiles that add images etc. if you choose to regenerate common files in the maintenance section..
	const Overwrite_page_class=Cfg_master::Overwrite;//Currently using setting in Cfg_master parent..  Page class file referes to a file which can be customized to override or add to main system functions, add header scripts and other files on a per page basis.  
     const Debug_backtrace=Cfg_master::Debug_backtrace;//For error logging backtrace...optionally refer to value set in Cfg_master.class.php or set true false here
	const Error_exit=Cfg_master::Error_exit;//if set to true exits following call to error_handler.php it optionally  exits on non fatal errors  refer to value set Cfg_master.class.php or set true false here 
}
?>